# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build and archive the app"
  lane :build do
    build_app(
      scheme: "MindPulse", # Make sure this matches your actual scheme
      export_method: "app-store"
    )
  end

  desc "Distribute to TestFlight"
  lane :beta do
    increment_build_number
    build_app(
      scheme: "MindPulse"
    )
    upload_to_testflight
  end

  desc "Deploy to the App Store"
  lane :release do
    capture_screenshots               # Optional
    build_app(
      scheme: "MindPulse",
      export_method: "app-store"
    )
    upload_to_app_store
  end
end

